### ISSUE TITLE
not view overlay

### ISSUE THREAD

**Issue by Freddereck** [haxgun/Valory#3]
Загружаю свой ник, там есть японский символ. 
TFH 厶 Fredderick#6666

Result:
![image](https://github.com/haxgun/Valory/assets/75345483/c2327579-4d63-467e-ae0d-1c26e2b0b9f5)

**Comment by myd4na** [comment]
![image](https://github.com/haxgun/Valory/assets/163687817/952e3af5-a029-49bb-a669-88280e1bc173)
same problem
